# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CSVtoStatProcessing
                                 A QGIS plugin
 Read a CSV file and calculate the number of lines for each item in the specified column
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-05-15
        copyright            : (C) 2020 by Yoichi Kayama
        email                : yoichi.kayama@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Yoichi Kayama'
__date__ = '2020-05-15'
__copyright__ = '(C) 2020 by Yoichi Kayama'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CSVtoStatProcessing class from file CSVtoStatProcessing.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .QGISStatProcessing import QGISStatProcessingPlugin
    return QGISStatProcessingPlugin()
