# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CSVStaticMeshAggre
                                 A QGIS plugin
 Read a CSV file and calculate the number of lines for each item in the specified column
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-05-15
        copyright            : (C) 2020 by Yoichi Kayama
        email                : yoichi.kayama@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yoichi Kayama'
__date__ = '2020-12-11'
__copyright__ = '(C) 2020 by Yoichi Kayama'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import ( QCoreApplication ,
                           QVariant)

from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingException,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterVectorDestination,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterBoolean,
                       QgsProcessingParameterField,
                       QgsProcessingParameterNumber,
                       QgsProcessingOutputVectorLayer,
                       QgsVirtualLayerDefinition,
                       QgsVectorLayer,
                       QgsProcessingUtils,
                       QgsProcessingMultiStepFeedback,
                       QgsWkbTypes,
                       QgsField,
                       QgsFields,
                       QgsFeature,
                       QgsProcessingParameterString)


import processing
import sqlite3
import csv

from .mod import  agtools
#SplitMeshLayer( last_output ,  meshid  )

class CSVStatMeshAggreProcessingAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'

    #ENCODING = 'ENCODING'

    #encode = ['SJIS','UTF-8']

    proportional_div = ['人口','面積']


    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        self.addParameter(
            QgsProcessingParameterFile(
                self.INPUT,
                'CSVファイル',
                extension='csv'
            )
         )
        #  encoding of input file
        #encParam = QgsProcessingParameterEnum(
        #        self.ENCODING,
        #        'CSVファイルエンコーディング'
        #    )

        #encParam.setOptions(self.encode)
        #encParam.setAllowMultiple(False)
        #encParam.setDefaultValue(QVariant('SJIS'))
        #  file encoding
        #self.addParameter(
        #    encParam
        #)
        self.addParameter(QgsProcessingParameterEnum('ENCODING', 'CSVファイルエンコーディング', options=['SJIS','UTF-8'], allowMultiple=False, defaultValue='SJIS'))



        self.addParameter(QgsProcessingParameterVectorLayer('addresslayer', '住所レイヤ',
                         types=[QgsProcessing.TypeVectorPolygon], defaultValue=None))
        self.addParameter(QgsProcessingParameterField('addressfield', '住所フィールド', 
                         type=QgsProcessingParameterField.String, parentLayerParameterName='addresslayer', allowMultiple=False, defaultValue=None))

        self.addParameter(QgsProcessingParameterVectorLayer('meshlayer', 'メッシュレイヤ',
                         types=[QgsProcessing.TypeVectorPolygon], optional=False, defaultValue=None))
        
        self.addParameter(QgsProcessingParameterField('meshid', 'メッシュIDフィールド', 
                         type=QgsProcessingParameterField.String, parentLayerParameterName='meshlayer', optional=False, allowMultiple=False))


        self.addParameter(QgsProcessingParameterNumber('limit_sample', '最小サンプル数',
                          defaultValue=3))

        self.addParameter(QgsProcessingParameterNumber('maxdivide', '最大分割回数',
                          defaultValue=8))

        self.addParameter(QgsProcessingParameterBoolean('uneven_div', '不均等分割',
                          defaultValue=False))

        #  propotinal division method
        #propParam = QgsProcessingParameterEnum(
        #        "PROPDIV",
        #        self.tr('按分方法選択')
        #    )

        #propParam.setOptions(self.proportional_div)
        #propParam.setAllowMultiple(False)
        #propParam.setDefaultValue(QVariant('人口'))
        #  file encoding
        #self.addParameter(
         #   propParam
        #)

        #self.addParameter(QgsProcessingParameterVectorLayer('poplayer', '人口レイヤ',
        #                 types=[QgsProcessing.TypeVectorPolygon], optional=True,  defaultValue=None))
        #self.addParameter(QgsProcessingParameterField('popfield', '人口フィールド', 
        #                 type=QgsProcessingParameterField.String, parentLayerParameterName='addresslayer', optional=True, allowMultiple=False, defaultValue=None))
        


        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Output layer')
            )
        )

    def processAlgorithm(self, parameters, context, model_feedback):
        """
        Here is where the processing itself takes place.
        """
        results = {}

        feedback = QgsProcessingMultiStepFeedback(1, model_feedback)

        csvfile = self.parameterAsFile(
            parameters,
            self.INPUT,
            context
        )
        if csvfile  is None:
            raise QgsProcessingException(self.tr('csv file error'))

        #df = QgsVirtualLayerDefinition()

        enc = self.parameterAsInt(           
            parameters,
            'ENCODING',
            context)

        #enc = self.parameterAsFile(
        #    parameters,
        #    self.ENCODING,
        #    context
        #)
        meshLayer = self.parameterAsVectorLayer(
            parameters,
            "meshlayer",
            context
        )
        if meshLayer  is None:
            raise QgsProcessingException(self.tr('mesh layer missed'))

        meshidfields = self.parameterAsFields  (
             parameters,
             'meshid',
             context
        )


        limit_sample = self.parameterAsInt ( parameters,
             'limit_sample',
             context)

        maxdivide = self.parameterAsInt ( parameters,
             'maxdivide',
             context)

 
        uneven_div = self.parameterAsInt ( parameters,
             'uneven_div',
             context)

                   


        feedback.setCurrentStep(1)
        if feedback.isCanceled():
            return {}

        # 住所別集計
        alg_params = {
        
            'addresslayer': parameters['addresslayer'],
            'addressfield': parameters['addressfield'],
            'INPUT': csvfile,
            'ENCODING': enc,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }

        #Stat_CSVAddressPolygon

        outputs_statv = processing.run('QGIS_stat:Stat_CSVAddressPolygon', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        if feedback.isCanceled():
            return {}

        statv = outputs_statv["OUTPUT"]
        meshid = meshidfields[0]
        param1 = { 'INPUT' : statv, 
                 'OUTPUT' : QgsProcessing.TEMPORARY_OUTPUT, 'aggrefield' : 'count', 
                'limit_sample' : limit_sample , 'meshid' : meshid,
                'meshlayer' : meshLayer, 'uneven_div' : uneven_div}
        
        #parameters['OUTPUT']
        #     メッシュ集計
        res1 = processing.run('QGIS_stat:AggregateAdmbyMeshAlgorithm', param1, context=context, feedback=feedback, is_child_algorithm=True)

        if feedback.isCanceled():
            return {}


        

        numberof_under_limit = res1["LIMITPOL"]

 #  分割回数ループ

                        # レイヤをGeoPackage化
        alg_paramsg = {
                           'LAYERS': res1["OUTPUT"],
                           'OVERWRITE': True,
                          'SAVE_STYLES': False,
                           'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                           }
        retg1 = processing.run('native:package', alg_paramsg, context=context, feedback=feedback, is_child_algorithm=True)
        last_output = retg1["OUTPUT"]

        new_mesh = retg1["OUTPUT"]




        for divide_c in range(1,maxdivide ):

            #   集計結果が最小サンプルより小さいものがある場合
            if numberof_under_limit > 0:
                   #  均等分割の場合は終了
                   if not uneven_div:

                       break

                   #  不均等分割の場合は終了終了データを保全  それ以外のメッシュの分割
                   #else:

            #  最小サンプルより小さいものが無い場合はメッシュ分割
            else:
                   new_mesh = agtools.SplitMeshLayer( last_output ,  meshid  )


             
            #  再度メッシュ集計
                   param2 = { 'INPUT' : statv, 
                        'OUTPUT' : QgsProcessing.TEMPORARY_OUTPUT, 'aggrefield' : 'count', 
                        'limit_sample' : limit_sample , 'meshid' : meshid,
                        'meshlayer' : new_mesh, 'uneven_div' : uneven_div}

                   res2 = processing.run('QGIS_stat:AggregateAdmbyMeshAlgorithm', param2, context=context, feedback=feedback, is_child_algorithm=True)

                   numberof_under_limit = res2["LIMITPOL"]

                   if numberof_under_limit == 0:

                       
                       # レイヤをGeoPackage化
                       alg_paramsg2 = {
                           'LAYERS': res2["OUTPUT"],
                           'OVERWRITE': True,
                          'SAVE_STYLES': False,
                           'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                           }
                       retg2 = processing.run('native:package', alg_paramsg2, context=context, feedback=feedback, is_child_algorithm=True)
                       last_output = retg2["OUTPUT"]



        
        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.

       



        results["OUTPUT"] = last_output
        return  results


    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'CSVStatMeshAggreProcessingAlgorithm'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return 'CSVメッシュ別集計(面積按分)'

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return '集計'

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return self.tr('Aggregate')

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return CSVStatMeshAggreProcessingAlgorithm()
