# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CSVtoStatProcessing
                                 A QGIS plugin
 Read a CSV file and calculate the number of lines for each item in the specified column
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-05-15
        copyright            : (C) 2020 by Yoichi Kayama
        email                : yoichi.kayama@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yoichi Kayama'
__date__ = '2020-05-15'
__copyright__ = '(C) 2020 by Yoichi Kayama'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import QgsProcessingProvider
from .CSVtoStatProcessing_algorithm import CSVtoStatProcessingAlgorithm
from .StatCSVProcessingAlgorithm import StatCsvProcessingAlgorithm
from .CreateSumSqlProcessingAlgoritm import CreateSumSqlProcessingAlgorithm
from .CSVStaticMeshAggre  import CSVStatMeshAggreProcessingAlgorithm
from .AggregateAdmbyMeshAlgorithm import AggregateAdmbyMeshAlgorithm
#from .AggregateAdmbyMeshMainAlgorithm import AggregateAdmbyMeshMainAlgorithm



class QGISStatProcessingProvider(QgsProcessingProvider):

    def __init__(self):
        """
        Default constructor.
        """
        QgsProcessingProvider.__init__(self)

    def unload(self):
        """
        Unloads the provider. Any tear-down steps required by the provider
        should be implemented here.
        """
        pass

    def loadAlgorithms(self):
        """
        Loads all algorithms belonging to this provider.
        """
        self.addAlgorithm(CSVtoStatProcessingAlgorithm())
        self.addAlgorithm(StatCsvProcessingAlgorithm())
        self.addAlgorithm(CreateSumSqlProcessingAlgorithm())
        self.addAlgorithm(CSVStatMeshAggreProcessingAlgorithm())
        self.addAlgorithm(AggregateAdmbyMeshAlgorithm())
        #self.addAlgorithm(AggregateAdmbyMeshMainAlgorithm())

        # add additional algorithms here
        # self.addAlgorithm(MyOtherAlgorithm())

    def id(self):
        """
        Returns the unique provider id, used for identifying the provider. This
        string should be a unique, short, character only string, eg "qgis" or
        "gdal". This string should not be localised.
        """
        return 'QGIS_stat'

    def name(self):
        """
        Returns the provider name, which is used to describe the provider
        within the GUI.

        This string should be short (e.g. "Lastools") and localised.
        """
        return self.tr('NICT')

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        return QgsProcessingProvider.icon(self)

    def longName(self):
        """
        Returns the a longer version of the provider name, which can include
        extra details such as version numbers. E.g. "Lastools LIDAR tools
        (version 2.2.1)". This string should be localised. The default
        implementation returns the same string as name().
        """
        return self.name()
